version: '3.5'
services:
  mq_backend:
    #image: python:3
    image: mq_python
    build:
      context: Back_end
      dockerfile: Dockerfile
    volumes:
      - "${PWD}/WORKSPACE:/uploads"
      - "${PWD}/Back_end:/app"
    working_dir: /app
    ports:
      - "5003:5000"
    depends_on:
      - mq_redis
    restart: always
  #  entrypoint: ["python", "/app/app.py"]
    entrypoint: ["bash", "/app/start.sh"]

  mq_redis:
    image: redis:alpine3.17
    ports:
      - "6379:6379"
    restart: always


  mq_nginx:
    image : nginx:alpine
    depends_on:
      - mq_backend
    restart: always
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/Front_end/build:/usr/share/nginx/html
    ports:
      - "9001:80"


