version: '3.5'
services:
  mq_backend:
    #image: python:3
    image: mq_python_dev
    build:
      context: Back_end
      dockerfile: Dockerfile_dev
    volumes:
      - "${PWD}/WORKSPACE:/uploads"
      - "${PWD}/Back_end:/app"
    working_dir: /app
    ports:
      - "5004:5000"
    depends_on:
      - mq_redis
        #entrypoint: ["python", "/app/app.py"]
    entrypoint: ["sh", "/app/start.sh"]

  mq_frontend:
    image: node:gallium-bullseye
    #image: nbmaiti/node-front_alpine_prod

##    build:
##      context: Front_end
##      dockerfile: Dockerfile
    volumes:
      -  ${PWD}/Front_end:/app
    working_dir: "/app"
    entrypoint: ["yarn", "start"]
    ports:
      - "9005:9000"
    depends_on:
      - mq_backend
    restart: always

  mq_redis:
    image: redis:alpine3.17
    ports:
      - "6378:6379"
    restart: always


  mq_nginx:
    image : nginx:alpine
    depends_on:
      - mq_backend
      - mq_frontend
    restart: always
    volumes:
      - ${PWD}/nginx/default-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9001:80"




